### ISSUE TITLE
[Insight] Source code should not contain FIXME comments - in config/…/dev/easy_log_handler.yaml, line 6

### ISSUE THREAD

**Issue by reashetyrr** [CaveNetwork-Inc/website#3]
**[in config/packages/dev/easy_log_handler.yaml, line 6](https://github.com/CaveNetwork-Inc/website/blob/aec8505c326808ab5c7f77dc458eb1f8c02a8a7f/config/packages/dev/easy_log_handler.yaml#L6)**

> FIXME comments are left in the code when a bug has been noticed but not fixed. You should fix the bug and remove the comment.

```
services:
    EasyCorp\EasyLog\EasyLogHandler:
        public: false
        arguments: ['%kernel.logs_dir%/%kernel.environment%.log']

#// FIXME: How to add this configuration automatically without messing up with the monolog configuration?
#monolog:
#    handlers:
#        buffered:
#            type:     buffer
#            handler:  easylog
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d74c5c9c-a0d5-46e5-9f23-466427ef6701/analyses/1)_
